apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa-admin
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-rolebinding
  namespace: devops-tools
subjects:
  - kind: ServiceAccount
    name: jenkins-sa-admin
    namespace: devops-tools
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
