pipeline {
    agent any

    tools {
        go 'go-1.20'
    }

    environment {
        GOPATH = '/home/jenkins/go'
        GO111MODULE = 'on'
    }

    stages {
        stage('Test') {
            steps {
                git '<github url>'
                sh 'go test ./...'
            }
        }

        stage('Build') {
            steps {
                git '<github url>'
                sh 'go build .'
            }
        }

        stage('Run') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/<job name> && <job name> &'
            }
        }
}
